[package]
name = "flobot"
version = "0.2.0"
authors = ["Florent Peterschmitt <florent@peterschmitt.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "flobot"
path = "src/lib/lib.rs"

[dependencies]
ws = {version = "*", features = ["nativetls"]}
dotenv = "*"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
crossbeam = "0.7"
diesel = { version = "1.4", features = ["sqlite"] }
diesel_migrations = { version="1.4", features= ["sqlite"]}
r2d2 = "*"
r2d2_sqlite = "*"
regex = "*"
reqwest = { version = "*", features = ["blocking", "json"] }
