[package]
name = "flobot-lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
reqwest = "0.11"
regex = "1.5"
serde = "1.0"
serde_json = "1.0"